### ISSUE TITLE
Text does not work with current Geckoboard API anymore, 'type' is supposed to be an int

### ISSUE THREAD

**Issue by kdejongh** [geckoboard-java-api/geckoboard-java-api#7]
Example:

 Sending: {"data":
{"item":[{"text":"21.04.2015: .......","type":"2"},{"text":"24.04.2015: ........","type":"2"}]},
"api_key":"...."}

Error sending json, error: {"message":"invalid type provided: expected \"int\", got \"string\""}

**Comment by kdejongh** [comment]
seems to work in the current version ;>)

**Comment by pvanassen** [comment]
Yes, I need to release the latest version.
